### ISSUE TITLE
Incorrect RSSI stored in database (Exposure Notifications)

### ISSUE THREAD

**Issue by mh-** [microg/android_packages_apps_GmsCore#1230]
If [this](https://github.com/microg/android_packages_apps_GmsCore/blob/d3d04459d66a0b7a357cffa3bdca84a21e4e0cd1/play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureDatabase.kt#L132) is meant to update RSSI with the average of old and new value, it doesn't work. I get -9223372036854775808 (the minimum `long` value) from the database.

```
fun noteAdvertisement(rpi: ByteArray, aem: ByteArray, rssi: Int, timestamp: Long = Date().time) = writableDatabase.run {
        val update = compileStatement("UPDATE $TABLE_ADVERTISEMENTS SET rssi = ((rssi * duration) + (? * (? - timestamp - duration)) / (? - timestamp)), duration = (? - timestamp) WHERE rpi = ? AND timestamp > ? AND timestamp < ?").run {
            bindLong(1, rssi.toLong())
            bindLong(2, timestamp)
            bindLong(3, timestamp)
            bindLong(4, timestamp)
            bindBlob(5, rpi)
            bindLong(6, timestamp - ALLOWED_KEY_OFFSET_MS)
            bindLong(7, timestamp + ALLOWED_KEY_OFFSET_MS)
            executeUpdateDelete()
        }
```

**Comment by mar-v-in** [comment]
Thanks for reporting. Seems there is a closing paren at the wrong spot. Will fix asap.

**Comment by mh-** [comment]
@mar-v-in thanks! I also would like to add that this RSSI handling is significantly different from what Google does. 
Google stores each scan with its own RSSI and AEM in a list of sightings, with (date-prefix plus RPI) as the key, into a database. 
When retrieving this later, they can calculate the minimum attenuation as well, not only the average.

**Comment by mar-v-in** [comment]
Yes, I am aware of that. However this information isn't used for risk calculation so back then when there only was v1 mode, there was no need to store this information. To support ExposureWindow mode we'd need to change how we store scan information in the database anyway.

The microG implementation doesn't completely match the Google implementation due to lack of proper specification and documentation at that point. This indeed changed to some degree, so it would make sense to update the implementation accordingly once there is time to do it. However until now I'm happy if we have results that are sufficiently similar.

**Comment by mh-** [comment]
Makes sense. 

The reason why I’m interested in this:
Within the [Warn-App-Companion app](https://github.com/mh-/corona-warn-companion-android) I added an option to import your database (a feature request by a user). 
It would be nice if you could add a short hint to this issue when you change the database implementation.

**Comment by mar-v-in** [comment]
@mh- sure, I can ping you once we do any database changes.
