### ISSUE TITLE
Can’t manage to get Cerberus work with GmsCore

### ISSUE THREAD

**Issue by bateast** [microg/android_packages_apps_GmsCore#125]
Hi,
I have Cerberus (https://www.cerberusapp.com/) installed as a system application (flashed from recovery).
It does not receive push messages from servers. I get this log :
`04-26 16:41:11.133 W/BroadcastQueue(3969): Permission Denial: receiving Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x30 pkg=com.lsdroid.cerberuss
cmp=com.lsdroid.cerberuss/com.lsdroid.cerberus.C2DMReceiver (has extras) } to com.lsdroid.cerberuss/com.lsdroid.cerberus.C2DMReceiver requires com.lsdroid.cerberuss.permission.C2D_MESSAGE due to sender
com.google.android.gms (uid 10064)`

which seems to tell that cerberus has a missing permission, but why is it failling with microg and not stock google services ?

Thanks.
##

**Comment by n76** [comment]
My guess would be that Cerberus has to be installed after GmsCore but since you have it as a system app and GmsCore is likely not a system app in your installation it looks to be installed later.

I believe that if you install gapps that at least some of the functionality provided by GmsCore is installed in /system so it would react differently.

You might try to install GmsCore as a system app using recovery at the same time as you install Cerberus to see if that makes a difference.

**Comment by bateast** [comment]
Hi,

thank you for your comment. Unfortunately, no luck.
I installed gsmcore and gsf as system apps, completely wipe out cerberus, (reboot), installed cerberus as a normal app,
still same symptoms …
What can I provide to hep debugging ?

Actually, not being able to use Cerberus could be a killer for using microg for me …

Thanks again,

**Comment by ale5000-git** [comment]
@bateast: Try the latest version, currently 0.2.4-28

**Comment by bateast** [comment]
Hi, still no good :(

again, what type of logs or information may I provide you for further analysis.
BTW, did you managed to get it work, that is having a Cerberus application installed as a system app, reachable remotely on demand via https://www.cerberusapp.com/.

Thank you

**Comment by ale5000-git** [comment]
Try to install Cerberus, restart phone, reinstall it as normal app and only when it is working move to system.

**Comment by bateast** [comment]
It is working with that !
Thank you.
