### ISSUE TITLE
WiFi Sherlock crash

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#157]
The application start normally at first but after you login successfully with the Foursquare account (or also as guest) it crash.
Please tell me what info do you need.

**Comment by ale5000-git** [comment]
The app is in the play store or also here: https://apkpure.com/wifi-sherlock-wifi-finder/com.fisherman.wifisherlock

**Comment by ale5000-git** [comment]
The logcat of the crash is here: https://www.zerobin.net/?5b74169d5d4acddf#sE4QYQ3kJBn5HdgBaHCLaYcd2Xv88wZV0/AyJAVu+xU=

**Comment by mar-v-in** [comment]
You pushed GmsCore into /system or installed it using some flashable zip file.This is not supported and can cause various problems when loading native libraries.

Install GmsCore as usual app instead as described in the wiki.

**Comment by ale5000-git** [comment]
I have reinstalled it from F-Droid, now there is another crash, possibly different but I'm not sure.
These seems relevant:

1) [ 07-31 17:21:33.000  5406: 5417 D/SafeParcel ]
Unknown field num 9 in com.google.android.gms.common.internal.GetServiceRequest, skipping.

2) [ 07-31 17:21:33.578  6512: 6512 W/GmsMapView ]
java.lang.NoSuchFieldException: primaryCpuAbi
......

3) [ 07-31 17:21:34.039  6512: 6512 W/GmsMapImpl ]
Compass not yet supported

4) [ 07-31 17:21:34.039  6512: 6512 W/GmsMapImpl ]
ZoomControls not yet supported

5) [ 07-31 17:21:34.281  6512: 6512 W/GmsMapImpl ]
MyLocation not yet supported


The full logcat is here: https://www.zerobin.net/?1db480e721bbd82a#v7HPDbJ1wcx6YGNIScRiuL3jZDeVqVvIccO7Z6uJVSQ=

**Comment by mar-v-in** [comment]
This might be related to #159, can you try with 0.2.4-3+?

**Comment by ale5000-git** [comment]
Sorry, I thought I was already on the latest but I wasn't.
Niow I have updated and the crash is fixed but there are still the not supported things and in addition also:
Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.

If you need help identifying these unknown fields just send me a version with additional debug infos and I will help.

**Comment by mar-v-in** [comment]
Unknown field num messages usually mean that the implementation of microG is not 100% up-to-date with the original Google implementation. However, there are certain features that make sure that even in those cases, microG will continue to run and provide the best possible output. e.g. if Google adds a feature to rotate a marker on the z axis when shown on the map, this will become a new field in MarkerOptions that is unknown to microG. Instead of crashing it will just ignore the z axis rotation and thus render it slightly wrong. There are a lot of these small changes every now and then and some of them are unlikely to be ever implemented ;) Especially in Maps API, there are huge changes to be done as the rendering library used there is no longer updated upstream and we'd like to switch to another one soon.

**Comment by ale5000-git** [comment]
I'm closing this since the original problem is fixed.
