### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by Nutomic** [microg/android_packages_apps_GmsCore#161]
I'm aware that this app is available in your own F-Droid repo. However, it would be great if it was also available in the default F-Droid repo.

A request thread on the F-Droid repo is [here](https://f-droid.org/forums/topic/android_packages_apps_gmscore/).

Is there anything preventing such a release, or is it just a matter of opening a PR with the metadata on F-Droid?

Btw, FakeStore and microG Services Framework Proxy also seem to be missing from the default F-Droid repo.

**Comment by ibleedbinari** [comment]
There are multiple issues related to duplicate packages and signature spoofing preventing this from happening at the moment. See #92 and #137

**Comment by mar-v-in** [comment]
We can't have microG GmsCore and UnifiedNlp in F-Droid at the same time. This is not planned to be fixed soon. FakeStore and Services Framework Proxy are not useful as standalone, so it's not a good idea to have them in the repo without GmsCore. As GmsCore required system modifications before being used, it is unlikely that UnifiedNlp will be replaced by GmsCore soon. We might want to reconsider this once GmsCore is a bit more stable and has a better UI that is easier to use.

With Phonesky, there will be an alternative Play Store client integrated in the microG project and it will contain easy updating mechanisms for microG (and possibly even F-Droid integration, so you can download apps from F-Droid repos instead of Google Play). However Phonesky is still very unfinished, so don't consider this to be done soon.

**Comment by Nutomic** [comment]
That sounds good. Do you have some kind of roadmap, or a WIP implementation somewhere?
