### ISSUE TITLE
"Push Notification Tester" asking To "Update Google Play Services"

### ISSUE THREAD

**Issue by rjawaid** [microg/android_packages_apps_GmsCore#193]
Hi,

I'm using microg on ominrom.  As per the thread on XDA I was trying to test push notifications but I'm receiving "Update Google Play Services" message on "Push Notification Tester" app.  It also has red X next to "Play Services Installed" in the check list. Everything else is green ticks.  Even in microg setting everything is checked green in "Self Check".  Please help.

**Comment by mar-v-in** [comment]
Update to latest preview build or wait for 0.2.5 release, probably next weekend

**Comment by rjawaid** [comment]
Many thanks. You are a star

**Comment by theScrabi** [comment]
Might [this](https://github.com/microg/android_packages_apps_GsfProxy/issues/3) be a related issue?

**Comment by ale5000-git** [comment]
Try update it to 0.2.4-28 [here](https://microg.org/download.html).

**Comment by theScrabi** [comment]
I guess I already use this version.

[<img src="https://cloud.githubusercontent.com/assets/1891273/20623138/7fd4b27a-b306-11e6-8ce7-a631b4de2482.png" width=200>](https://cloud.githubusercontent.com/assets/1891273/20623138/7fd4b27a-b306-11e6-8ce7-a631b4de2482.png)

**Comment by danielegobbetti** [comment]
@theScrabi no you don't. If you look next to the "starten" button it says version 0.2.4 is installed and 0.2.4-28 is available (but that part is truncated). Then to the bottom of the string you see that version 0.2.4-28 is "nicht installiert" (not installed).

It happens because this release is not automatically selected as update by fdroid, if you tap the 0.2.4-28 entry that you see at the bottom of the screen it will update.

**Comment by theScrabi** [comment]
Ah I see It's a common layer 8 error. Hm may have to fix that one day :)
thanks
