### ISSUE TITLE
Getting Ingress working

### ISSUE THREAD

**Issue by JonnyTech** [microg/android_packages_apps_GmsCore#220]
I am new to microg and am having difficulty finding enough documentation. Can someone please post step-by-step instructions for going from a clean CM13 install to having micog installed and working with Ingress. I got stuck at signature spoofing and was not sure about stores and maps api. Any guidance is greatly appreciated. Thanks in advance.

**Comment by ArchangeGabriel** [comment]
I would say:

– Patch your ROM for signature spoofing, using Tingle. This requires to give root rights to ADB in CM developer options menu.

– Install microG GMS Core from F-Droid microg.org repo.

– Install either BlankStore or FakeStore.

– Install the unifiedNlp backends you want to make use of.

**Comment by JonnyTech** [comment]
Thank you very much, I had missed the F-Droid repo, looks easier than I thought.

Is one store better than another? I like the look of BlankStore but are either still active?

Which unifiedNlp backends are recommended? Must I install NetworkLocation.apk first?

Just found other instructions at https://android.izzysoft.de/articles/named/android-without-google-5a which may help.

**Comment by ArchangeGabriel** [comment]
FakeStore is no store, just a dummy APK to let other apps think that there PlayStore is installed. BlankStore is not developed anymore but works for most things. The future is Phonesky, but not usable yet. I personally use BlankStore on one device where I use quite a bunch of non-free apps (banking, travelling…), and FakeStore on another where they are mostly F-Droid apps.

Which unifiedNlp backends are recommended is mostly a question of taste. Personally, I ever go with LocalGSM and LocalWiFi ones, because they’re local. If NetworkLocation.apk is the unifiedNlp app, you must indeed remove it first, because it’s part of microG GMS Core. You might stumble upon this issue BTW: https://github.com/microg/android_packages_apps_GmsCore/issues/190 (nothing to worry about, just something to know).

The guide you’ve found is correct, note that it’s mostly based on the local wiki (https://github.com/microg/android_packages_apps_GmsCore/wiki) that I encourage you to read. ;)

**Comment by EleutheriusBliss** [comment]
Official Play store app working for me (except for purchasing non-free apps).

**Comment by YoBii** [comment]
As said above you can use official play store app. 
Also for NLP backends I'd recommend you Apple and Mozilla. Both are pretty close to the location you get with Googles location service.
You can also populate your own local databases as @ArchangeGabriel wrote.

Getting Ingress itself to work is really no problem. I had it running a couple of minutes after setting up microG.
