### ISSUE TITLE
Reverse Geocoding?

### ISSUE THREAD

**Issue by ArchangeGabriel** [microg/android_packages_apps_GmsCore#250]
Hi,

It seems that Play Services provide a reverse Geocoding API (the app send GPS coordinates, the API returns the name of this location). Could this be implemented in GmsCore? (Or maybe is that supposed to be in UnifiedNlp?)

Thanks!

**Comment by n76** [comment]
You just need to write a geocoder backend for UnifiedNLP. See https://github.com/microg/NominatimGeocoderBackend for an example of how to write one.

**Comment by ArchangeGabriel** [comment]
Do geocoder backends also provide reverse geocoding feature? If so why doesn’t NominatimGeocoderBackend do it, and would it be hard to add this feature to that backend?

**Comment by n76** [comment]
Its been a while since I read through that code, but yes, the backend does both geocoding and reverse geocoding.

Why doesn't the Nominatim backend do  it? It does. Or rather did. The problem is that it uses a service that now requires an API key and has not been modified to have one so all calls to the server for both coding and reverse coding fail. You can read the bug reports on that backend to understand more.

**Comment by ArchangeGabriel** [comment]
OK, closing this so, the real issue being Nominatim not working anymore.
