### ISSUE TITLE
Many Just Updated Apps are Requesting Google Play Services Be Updated

### ISSUE THREAD

**Issue by landry314** [microg/android_packages_apps_GmsCore#271]
The newest version of Signal, Wire, and Google Maps are all now asking at startup that google play services be updated. It appears that updating any of my apps that use GCM is causing annoying messages. The apps are working fine after the dialog is dismissed but the dialog will return again and again depending on the app...

I feel like if microG's GmsCore is updated somehow it will solve this. Just a guess. I am running the newest versions right off of the F-Droid repo and FakeGapps 1.1 in Xposed on Cyanogenmod 13.

Who else is having this problem?

**Comment by Caliandroid** [comment]
me too

**Comment by yepyepyep4711** [comment]
+1
I have it in Signal and Slack atm. As far as I can tell it happens whenever you update the "client" app. It's very cumbersome with Signal, cause it keeps putting a "Permanent Signal communication error" in your notification bar

**Comment by ale5000-git** [comment]
It would help if you post a logcat where it say exactly the version required.

**Comment by Caliandroid** [comment]
For example for the WARNWETTER app.
Push via GCM works fine but i receive everytime the info message, that GCM is missing:


01-15 22:40:35.133 28097-28097/? E/GMPM: GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
01-15 22:40:35.133 28097-28097/? E/GMPM: Scheduler not set. Not logging error/warn.
01-15 22:40:35.147 28097-28097/? V/ACRAWrapper: Acra is not enabled, because not signed with debug certificate
01-15 22:40:35.152 28097-28118/? E/GMPM: Uploading is not possible. App measurement disabled
01-15 22:40:35.309 28097-28097/de.dwd.warnapp D/cacheSize: 134217728
01-15 22:40:35.316 28097-28097/de.dwd.warnapp D/CacheUsedSize(): 44956
01-15 22:40:35.503 28097-28097/de.dwd.warnapp W/GooglePlayServicesUtil: Google Play Store signature invalid.
01-15 22:40:35.511 28097-28097/de.dwd.warnapp E/GoogleApiAvailability: Google Play services is invalid. Cannot recover.

**Comment by ale5000-git** [comment]
@Caliandroid: Your problem has nothing to do with the normal version check, I don't know exactly but I think it is a more serious problem.

It seems that the "signature spoofing" isn't working correctly.

**Comment by ale5000-git** [comment]
@Caliandroid: Your problem has nothing to do with the normal version check, I don't know exactly but I think it is a more serious problem.

It seems that the "signature spoofing" isn't working correctly.

What version of Play Store do you have?

**Comment by landry314** [comment]
I think it is pretty obvious that newer versions of many apps are now looking for a minimum version of Google Play Services which is lower than the one it is finding spoofed. On December 1 Google updated to 10.0.84.

Wouldn't an update of microG to incorporate some newer aspects of the updates or at least to simply spoof this newest version number fix the issue?

**Comment by mar-v-in** [comment]
@landry314 yes. just give me a few hours to manage it :)

**Comment by ale5000-git** [comment]
@landry314: Probably the issue of @Caliandroid is different since if I have read correctly the log it has nothing to do with version update.

**Comment by 3ex3** [comment]
If you install the Google app from the play Store do you still get these messages? I was getting them too and then they stopped at some point and everything works great now. All I can think of is that I installed the Google app recently. Google maps even works.

**Comment by 3ex3** [comment]
Also, could this be related to #232?

**Comment by ecanja** [comment]
I have just today tried for the first time to install microG and FakeGApps for using GCM and do have the same problem. I can't register with Signal, cause it requires me to update Play Services. Moreover, the Push Notification Tester app brings the same popup message and "Play Services installed" and "Register for Push Notifications" are missing (i.e. red cross instead of green checkmark).

As far as I can tell, I have installed the latest versions of the microG apps (through your F-Droid repository) and of the FakeGApps module.

I dived into the logcat and found these lines:
```
I/Xposed  ( 2796): FakeGApps: returning fake signature to org.thoughtcrime.securesms
I/Xposed  ( 2796): FakeGApps: returning fake signature to org.thoughtcrime.securesms
W/GooglePlayServicesUtil(15098): Google Play services out of date.  Requires 9683000 but found 9258259
V/WindowManager( 2796): not Base app: Adding window Window{3d3ecfa8 u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RegistrationActivity} at 7 of 13
```

Does this help in any way?

**Comment by mar-v-in** [comment]
Please try updating to the preview release 0.2.4-50, the next release 0.2.5, which will be there in a few days will also fix this problem.

**Comment by ecanja** [comment]
Sorry, just edited my comment: I already used 0.2.4-50 and didn't try with any other version, but it nevertheless doesn't work. :-(

**Comment by mar-v-in** [comment]
The log you posted says you are using version 9258259, which is 0.2.4, 0.2.4-50 would be 10087409. Check in microG settings -> about and make sure it says 0.2.4-50.

**Comment by ecanja** [comment]
Oh ok, F-Droid tells me something else. But then I'll have a look, thanks!

**Comment by Caliandroid** [comment]
It works for me after updating to your newest release 0.2.4-50 (+ activate permission for sign. spoofing to fakestore)

**Comment by alexbel** [comment]
I have version 0.2.4-55-g4c4086a and the "Update google services" notification disappeared. However, push notification don't work.Self-check says all the boxes are checked except Nlp related.

**Comment by spacekitteh** [comment]
I'm still getting this with version e4831e-dirty

**Comment by ale5000-git** [comment]
@landry314 @yepyepyep4711 @alexbel @spacekitteh

Have you tried with version 0.2.4-64?

**Comment by spacekitteh** [comment]
I tried with the master branch maybe, four hours ago.

**Comment by spacekitteh** [comment]
Perhaps the git submodule pointers are out of date?

**Comment by mar-v-in** [comment]
Dirty builds include local modifications. Can you check what is different in your copy by git status + git diff. Or maybe just clone the repo again.

Master builds should have a proper version attached as well, so something seems to be wrong if there is no 0.2.4-* at the beginning of your version.

**Comment by spacekitteh** [comment]
Marvin, the modified spoofing check.

**Comment by mar-v-in** [comment]
@spacekitteh 1. what apps are affected for you? 2. can you try if this problem persists when building from a standalone clone of the master (= not building as part of aosp). 3. can you upload the apk that does not work for you?

**Comment by ale5000-git** [comment]
@spacekitteh: e4831e isn't the latest master, the latest is 45e2d2

**Comment by spacekitteh** [comment]
Signal, for one. I think it's because it requires GmsLib installed, as it is using GooglePlayServicesUtil.

**Comment by mar-v-in** [comment]
Signal should work fine with GmsCore correctly build from master, so it's probably something about your build that's broken (or you are building the 0.2.4 tag and not master, which would be so old that this message is expectable).

**Comment by Torvin** [comment]
@mar-v-in are you planning to release 0.2.5 anytime soon? I mean, building manually is not that convenient

**Comment by mar-v-in** [comment]
@Torvin you are not required to build manually, I regularly push preview builds to the microG F-Droid repo, also available via https://microg.org/download.html dropdown button next to stable download.

There are a few bugs I want to fix before the 0.2.5 release, but it should be there in less than a month I guess...

**Comment by Torvin** [comment]
@mar-v-in thanks, I didn't realise that. I downloaded it directly from that page. I guess my confusion comes from the fact that you didn't tag these on GitHub.

Btw, I cannot find this package in FDroid, despite your repository being added. What package name should I look for?

**Comment by mar-v-in** [comment]
@Torvin There is a bug in F-Droid that sometimes hides microG GmsCore into "UnifiedNlp (no GAPPS)", due to being the same package name. You should be seeing UnifiedNlp in your F-Droid installed section. If you want to receive update notifications for preview releases you can enabled this in the F-Droid settings.

**Comment by Torvin** [comment]
@mar-v-in thanks again!

**Comment by landry314** [comment]
what you do is go to the settings in f-droid then turn on expert mode at the bottom and then unstable updates then back out and go to repositories in the menu and turn OFF the f-droid repository while leaving the microg repo ON. Back out to the main screen and update repositories with the circle arrow icon... once done, in "available" tab you should find the gmscore right there. install it! Voilà. dont forget to turn on the f-droid repo again if you want to get updates for all your other apps!

**Comment by landry314** [comment]
the newer version of f-droid is working differently and it seems you can't turn off the default f-droid repository. instead, to update microg, go to the "UnifiedNlp (no GAPPS)" to update micro gmscore. it will look like it is updating only the unifiednlp but it is updating both. you will see that at the install screen.

**Comment by treba123** [comment]
Just wanted to say that this (the new version) solved the issue for me. So I guess it can be closed?

**Comment by ale5000-git** [comment]
@landry314: Have you tried the latest version?
If it fix the problem it is time to close the issue :)

**Comment by landry314** [comment]
Yes, the beta version in f-droid fixes the issue.

**Comment by Awerick** [comment]
As this issues will reappear whenever the current version gets outdated, would it be possible to solve this also for the future?

Currently `microG` returns a constant version code and the "outdated version" issue is simply fixed by releasing a new `microG` update with a higher version code. Maybe one could include a button in `microG` that increases the version code to a higher value? By this every user could easily fix the issue without having to wait until a new `microG` update is available.

(Probably this idea should be in a new issue – but I think I already read the same idea somewhere here or on xda-developers, so I don't want to create a duplicate...)

**Comment by landry314** [comment]
i agree, this would be a good feature. if only microg could somehow check for the newest google play services version the requesting app was looking for...

but having to update microg is a good thing because the updates no doubt provide more feature and better stability as well.

BUT, these updates are "unstable versions" in f-droid and so they won't show up unless you change the f-droid settings meaning most people won't have an easy fix pop up. some people might have just given up and installed play services. i hope we get to a real release version soon.

**Comment by cRaZy-bisCuiT** [comment]
Same problem again! GCM checker, Telegram and Signal do not work. Any solutions?
