### ISSUE TITLE
SetupWizard crash: Add a dummy com.google.android.setupwizard

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#324]
After LineageOS update, the setup wizard get executed and if it find "com.google.android.gms" but not "com.google.android.setupwizard" it crash loop indefinitely.

Despite being already fixed yesterday in LineageOS, it would be a good idea to add a dummy "com.google.android.setupwizard" to avoid problems since there may be other ROMs with this problem.

**Comment by mar-v-in** [comment]
I don't know of any other ROM implementing their own setup wizard, but please correct me if I'm wrong on this...

**Comment by dk-zero-cool** [comment]
Even if there was, this would be an error with that wizard if it produced the same problem. Goggles setup wizard is a stand-alone application. No package should simply assume it's availability just because gms is. The correct way is to look for the wizard package specifically, which is why LineageOS fixed it. It has nothing to do with gms.

**Comment by mar-v-in** [comment]
Agree with @dk-zero-cool, closing issue.
