### ISSUE TITLE
Push notifications not working on OmniROM 8.1.0

### ISSUE THREAD

**Issue by AceChaos** [microg/android_packages_apps_GmsCore#551]
I just switched from LineageOS with MicroG to OmniROM on my Moto G4, I installed GmsCore, GsfProxy, and FakeStore from F-Droid, enabled signature spoofing for GmsCore and FakeStore, checked the boxes in MicroG settings and gave it all suggested permissions, disabled battery optimizations for GmsCore, and am not using AdAway, yet push notifs will not work. The push notification tester linked on the MicroG site puts X's rather than checkmarks next to Play Services installed and Register for Push Notifications. I did a full wipe/reflash of the ROM and made sure all steps were done in order, to no avail.

**Comment by viniciusmr** [comment]
+1, sorta?
Using standard Gapps here (open_gapps-arm64-8.1-nano-20180612), just switched to OmniROM on my OnePlus 3T (omni-8.1.0-20180610-oneplus3-WEEKLY), and the push notifications are abysmal. 
Right out of the box. I can't recall ever seeing this sort of behaviour before. I've  seen problems with notifications AFTER I've tried and tweaked with Doze, Xposed, Greenify, Amplify and so on, but never in the default out-of-the-box config. I've been around custom ROM's at least since 2012, and I've used Omni before on other devices. Clean flashed over and over again (even the data partition).

WhatsApp, Messenger and Telegram are pretty much worthless right now, since they only 'update' when I manually open the app and after a small delay I get to see the messages arriving and updating on-the-fly on the app. Other than that, I don't get any notifications of new messages, 90% of the time. Only very rarely there is one.

**Comment by Shadow53** [comment]
You'll need to wait for (or implement) Firebase support in Android, as apps are moving to that from GCM in Android Oreo.

**Comment by Lanchon** [comment]
move from GCM is compulsory for devs by google. are there any showstoppers
for a firebase implementation?

**Comment by zebala** [comment]
@Shadow53 Would downgrading back to Android Nougat make applications use the old GCM, i.e is Firebase an Oreo only thing? I'm using LOS15.1 microg ATM.

**Comment by Shadow53** [comment]
> Would downgrading back to Android Nougat make applications use the old GCM, i.e is Firebase an Oreo only thing?

Possibly? I am also using LOS 15.1 for microg and my girlfriend is using 14.1 because her device doesn't have official 15.1 yet, and she has apps registered to GCM that will not register on mine. A couple apps have registered for me though, namely ProtonMail and Steam.

Based on this observation and without looking at any Android source code, my **guess** is Oreo changed the *default* to FCM, while GCM is default in Nougat and below, though apps can choose which one(s) to support and possibly which are default for them.

> are there any showstoppers for a firebase implementation?

@Lanchon I think the main showstopper here is nobody working on the firebase implementation. I imagine other hurdles will come up once someone starts, but AFAIK no one is working on implementing or even documenting the behavior of Firebase.

**Comment by bam80** [comment]
Is there anywhere issue/topic to fundraising Firebase support in MicroG? I think we need this one at least

**Comment by JacobRoth** [comment]
Same issue here - latest Ominrom for Xperia X Compact, push notifications don't work even for Protonmail.

**Comment by chris42** [comment]
Please see Issue "GCM -> FCM Update needed for push messaging" #439
A patch (not fully functional) has been releases in newest microg version. Bountysource is also connected, if you want to support

**Comment by sm4rk0** [comment]
Can this be closed?

**Comment by godoftech** [comment]
Possible workaround:
https://github.com/microg/android_packages_apps_GmsCore/issues/631#issuecomment-429013399

**Comment by ale5000-git** [comment]
The problem should be fixed in recent versions of microG GmsCore, I'm closing this for now.
Please try it and report back.
