### ISSUE TITLE
"Signature spoofing" does not show up in system settings

### ISSUE THREAD

**Issue by zilti** [microg/android_packages_apps_GmsCore#554]
I've installed LineageOS for GApps with the link from your wiki. But when I go to Settings - Apps - Advanced - App Permissions, there is no signature spoofing - nor anywhere else for that matter.

**Comment by ale5000-git** [comment]
`LineageOS for GApps` doean't actually exist, there is `LineageOS` and `LineageOS for microG`.
Yout problem isn't related to microG since microG only use "signature spoofing", it doesn't add it to the ROM.

If you meant `LineageOS for microG` you should report it [here](https://github.com/lineageos4microg/docker-lineage-cicd/issues)

**Comment by zilti** [comment]
Yeah, I meant the latter. I'm tired... Thanks!
