### ISSUE TITLE
Some apps won't recognize `microG` as Google Play services

### ISSUE THREAD

**Issue by bertalanp99** [microg/android_packages_apps_GmsCore#615]
I have only switched to `microG` recently. I am using a Samsung Galaxy S6 (`zerofltexx`) phone with the `microG` fork of  `LineageOS 14.1`. Let me say that I absolutely love this project; recently I started switching to FOSS and freeing my android phone from *Google*'s claws is a big step.

However, there are still some proprietary apps that I would like to keep using, for example because I have a subscription for them. One of these apps is [*Spendee*](https://play.google.com/store/apps/details?id=com.cleevio.spendee). I have this app from the Yalp Store now.

Now as far as I understand, `microG` mimics *Google Play* services, so even apps requiring them should function. Is this what is referred to as 'spoofing'? Some apps, most importantly *Spendee* don't work for me, because I get this error:

```
Spendee won't run without Google Play services, which are not supported by your device.
```

I also had this problem with other proprietary apps such as *DigiCal* and *Inbox*, but those two won't even start (they give a slightly different error), whereas *Spendee* starts, but pushes this dialogue in my face after every interaction.

In the self check, everything is ticked, except 'Play Store (phonesky) has correct signature'. I have 'Google device registration' and 'Google Cloud Messaging' enabled.

I have included screenshots (although I explained everything).

**Is this intended behaviour? Is there a workaround for these apps? Thank you in advance!**

![41991874_242599686414226_2743130182423412736_n](https://user-images.githubusercontent.com/22181548/45699072-b7897800-bb69-11e8-9418-a13b585b3fe2.png)
![42045239_237569423608225_3164410244449173504_n](https://user-images.githubusercontent.com/22181548/45699073-b7897800-bb69-11e8-89af-fe36cfa09265.png)
![42100926_226718771534539_6530132714232741888_n](https://user-images.githubusercontent.com/22181548/45699074-b8220e80-bb69-11e8-815d-f9ae9d08f5b8.png)

**Comment by JonnyTech** [comment]
Which version of microg are you running? At the bottom of the settings page you will see a version number in the about section. The current version is: 0.2.5.12879

**Comment by bertalanp99** [comment]
I am using the current version: `0.2.5.12879`

**Comment by JonnyTech** [comment]
Ah, I see that you have not installed a play store equivalent. Please install one (I use FakeStore) and make sure that all boxes on the check screen are ticked.

**Comment by ArchangeGabriel** [comment]
> In the self check, everything is ticked, except 'Play Store (phonesky) has correct signature'.

This is exactly your issue. As @JonnyTech says, you should install FakeStore (it should normally have the spoofing signature right from the start on LineageOS4μG).

**Comment by bertalanp99** [comment]
I *do* have FaceStore installed, I got it from the F-Droid repo of `microG`

![42204425_311131166146588_8029014092230426624_n](https://user-images.githubusercontent.com/22181548/45700478-f3720c80-bb6c-11e8-86f1-848018649cde.png)

**Comment by ArchangeGabriel** [comment]
1. Did you reboot since installation?
2. Can you check if there is a Signature spoofing permission to be granted somewhere in applications permissions (generic menu, not per-app one)?

**Comment by bertalanp99** [comment]
1. I think so, but for the hell of it I have rebooted now, tried again, still got the dialogue. Then uninstalled FakeStore, reinstalled and rebooted again. The issue still persists.
2. I assume you mean the permissions menu I can get to by Settings > Apps > [gear icon] > App permissions. There is no such option there (see screenshot). Should I look somewhere else? I didn't find anything in per-app permissions either. FakeStore doesn't even request any permissions.

![Uploading 42101561_251625305539302_2994977594257965056_n.png…]()

**Comment by ArchangeGabriel** [comment]
I don’t know then… I don’t have a LineageOS4μG device currently, so I don’t remember if there was anything special to do. Maybe @ncorna could help here…

**Comment by ArchangeGabriel** [comment]
I meant @corna…

**Comment by tokariu** [comment]
I'm having the same issue as OP - with Wire for android and Lineageos 14.1 + microG. 
Wire released a new android version today and after updating, it does not detect Google Play Services anymore, and then it runs via websockets and drains the complete battery within hours..
The previous version of Wire had no problems detecting MicroG as google play services, it worked flawlessly. Now it just says I "don't have GPS installed, therefor (...)". 

I think Wire (and similar apps) changed some code or frameworks that depend on newer Google Play Services and microG is not on the same updated level. (I'm just guessing here, but it looks logically.)

If anyone knows how to fix it I'd be glad to hear, because all these programs running now on websockets and thats a catastrophe for the battery.

**Comment by tokariu** [comment]
The Problem seems to be fixed for me now. 
I updated to: lineage-14.1-20180912-microG-d855, cleared dalvik+cache, the rest is the same. Wire seems to correctly detect GPS again. (I will update if it stops working)

**Comment by Nanolx** [comment]
The root cause for this is that your Play Store (or Fake Store) did not have signature spoofing permission initially, as seen from your screenshots.

Apps always report `Play Services are missing`, BUT this message is vague. It CAN also mean `Play Store is missing`, which either means no Play/Fake Store is installed at all or without signature spoofing permission.

**Comment by bertalanp99** [comment]
Since then I did a complete wipe and reinstall. I don't have any such problems now.
