### ISSUE TITLE
car2go crashes on startup

### ISSUE THREAD

**Issue by deesnook** [microg/android_packages_apps_GmsCore#711]
I run LineageOS 15.1 for microG on a OnePlus 3T without GApps. So far, the car2go app (car sharing app that accesses maps) has worked fine. Since an update to v3.36.6, the app crashes on startup.

Any ideas?

LineageOS: v15.1-20190220-microG-oneplus3
microG: v0.2.6.13280
car2go: v3.36.6

**Comment by Riamse** [comment]
try `adb logcat`?

**Comment by Tentos** [comment]
I have (had?) the same problem - the crashes even started some car2go versions earlier.
As suggested by @Riamse, I have taken a logcat and stumbled upon this exception:

`03-03 16:56:10.062 20867 20867 E AndroidRuntime: FATAL EXCEPTION: main
03-03 16:56:10.062 20867 20867 E AndroidRuntime: Process: com.car2go, PID: 20867
03-03 16:56:10.062 20867 20867 E AndroidRuntime: com.car2go.rx.ViewActionException: Error: java.lang.Throwable
03-03 16:56:10.062 20867 20867 E AndroidRuntime: 	at com.car2go.rx.h$a.a(ViewActionSubscriber.kt:173)
...
03-03 16:56:10.062 20867 20867 E AndroidRuntime: Caused by: java.lang.SecurityException: Neither android.permission.ACCESS_COARSE_LOCATION nor android.permission.ACCESS_FINE_LOCATION granted.
03-03 16:56:10.062 20867 20867 E AndroidRuntime: 	at org.microg.gms.maps.GoogleMapImpl.setMyLocationEnabled(GoogleMapImpl.java:443)
03-03 16:56:10.062 20867 20867 E AndroidRuntime: 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$Stub.onTransact(IGoogleMapDelegate.java:285)
03-03 16:56:10.062 20867 20867 E AndroidRuntime: 	at org.microg.gms.maps.GoogleMapImpl.onTransact(GoogleMapImpl.java:617)
03-03 16:56:10.062 20867 20867 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:499)
03-03 16:56:10.062 20867 20867 E AndroidRuntime: 	at com.google.android.gms.internal.h.a.b(Unknown Source)
03-03 16:56:10.062 20867 20867 E AndroidRuntime: 	at com.google.android.gms.maps.a.af.b(Unknown Source)
03-03 16:56:10.062 20867 20867 E AndroidRuntime: 	at com.google.android.gms.maps.c.b(Unknown Source)
...`
There seems to be some permissions conflict regarding the location. After manually giving car2go the permission to get the current location, the app starts without crashing. (I had granted access to the location to microg, but not to car2go. The location is faked anyway for car2go because of XPrivacy Lua.)

**Comment by deesnook** [comment]
Same here, also with earlier versions of car2go. It works if you grant permission to access location services
