### ISSUE TITLE
Write access to GitHub Wiki pages

### ISSUE THREAD

**Issue by Unkodero** [microg/android_packages_apps_GmsCore#784]
Hi! Why any user can edit wiki pages? Its ok? 
![image](https://user-images.githubusercontent.com/8190380/58106188-5af6c500-7bf0-11e9-8ff8-79a1c1f51086.png)

**Comment by sm4rk0** [comment]
That's [the definition of Wiki](https://www.thefreedictionary.com/wiki):

> A collaborative website whose content can be edited by anyone who has access to it.

**Comment by mar-v-in** [comment]
This is intended as is. If you want to contribute, feel free to do so.

CC @tomchiverton

**Comment by voidstarstar** [comment]
Any spam in the wiki (as well as spam in the issues, pull requests, comments, etc.) is considered abuse and violates the Github Community Guidelines and Terms of Service.  Users can be [reported to Github here](https://github.com/contact/report-abuse).  Please see [this page](https://help.github.com/en/articles/reporting-abuse-or-spam) for more info.

@diamentowybiznes and @delet-this have contributed intentional or repeated spam in the last week, so I would recommend just reporting them.  These look like accounts there were created specifically for spamming.  I reverted their commits, but if you think this deserves a more permanent solution, you can report them here:
[Report diamentowybiznes](https://github.com/contact/report-abuse?report=diamentowybiznes+%28user%29)
[Report delet-this](https://github.com/contact/report-abuse?report=delet-this+%28user%29)
