### ISSUE TITLE
[BUG] Tinder can't fetch location

### ISSUE THREAD

**Issue by RoiArthurB** [microg/android_packages_apps_GmsCore#786]
Hello all ! o/

**The device**

LineageOS + microG (Android Pie) + Magisk on a oneplus3

**How to reproduce**

* Open Tinder
* Connect with Facebook (2FA)
* Allow location access
* Get error message 

**The error message is**

    Unable to fetch location. 
    Please check your location.
    [Code 16]

**Other usefull informations**

I almost pass the SafetyNet Check (ctsProfile: false, basicIntegrity: true)

Every other apps work just fine with location access (Google Maps, HERE WeGo, Uber, Grab, Snapchat, etc)

**Comment by wombatch** [comment]
It will work if you use an older level of Tinder, it some recent updates may have made it try to use some other google services.

**Comment by RoiArthurB** [comment]
Do you know any possible version code ? ^^'

**Comment by RoiArthurB** [comment]
Ok, going with a previous version worked! :p

I'm using Tinder 10.0.1 (code version on *Yalp Store* : **10000130** )

**Comment by davux** [comment]
Why is the bug closed? The fact that it doesn't work with newer versions is an issue, isn't it?

Also, version 10040229 works as well FYI.

**Comment by RoiArthurB** [comment]
Cause I have a fix to solve my problem (I was not using the last update with MapBox) and there is some workaround trying to fix bugs related to location picker.
Take this issue for example: #808

**Comment by x37-potter** [comment]
I am also getting an issue with tinder 10.18.0 after logging in: 'Unable to fetch location. Please check your internet connection. Code: 16.'
Installed through Aurora Store, on ArrowOS & Moto G5 Plus
I tried versions 10040229 & 10000130 but they crash on start.
Issue is also mentioned here: https://github.com/microg/android_packages_apps_GmsCore/issues/801

**Comment by ale5000-git** [comment]
Could all of you update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry please?

**Comment by x37-potter** [comment]
Doesn't seem to be working for me.
Tinder 10180090 is crashing at start. 
I'll send the log.

**Comment by ale5000-git** [comment]
I'm not completely sure but maybe you missing a permission grant in your ROM.

From your log:
`I/[INFO][Leanplum](11524): [com.leanplum.LocationManagerImplementation::startLocationClient::10]: You have to set the application meta data and location permission to use location services.`

**Comment by ale5000-git** [comment]
@x37-potter: Instead of this closed issue, write in this: #801

**Comment by pangyuehung** [comment]
Interestingly, I get this specifically with Tinder installed through the Huawei AppGallery, so it should not have any dependencies on any Google Mobile Services and would instead depend on HMS Core. My error code is different as well:

> Oops
> 
> Unable to fetch location.
> Please check your internet connection.
> [Code: 10808]
> 
> Try Again

![Screenshot_2023-08-06-15-04-12-01_fe657d718f12c74f5142081a66e15273](https://github.com/microg/GmsCore/assets/70787764/c31956a4-27eb-44ac-888d-6d90f2a03fc4)

I have not installed MicroG installed to my knowledge, but when I add the F-Droid repo to my phone, it appears to already be installed—as tapping on the latest listed version of either "microG Services Core" or "FakeStore MicroG Store" in the repo shows a button to "downgrade" while "microG Services Framework Proxy" shows one possible version which is apparently already installed. 

Does this mean that Huawei Mobile Services uses microG, or have I somehow unintentionally transferred these over from my old phone? I am surprised by this issue because Huawei's Petal Maps also installed through the Huawei AppGallery seems to pick up my location perfectly.

**Comment by ale5000-git** [comment]
No, it is simply that microG to work it has to have the same internal names of Google Play Services, so the real Google Play Services is mistaken as microG by F-Droid.

It is possible that Huawei Mobile Services use the same internal name but I doubt it is using microG.
