### ISSUE TITLE
Android O+ account restrictions message

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#791]
@mar-v-in

On 30ed2720a0ecd3067fe760e801ecbdbe1b5ff5be the message is "Allow to bypass Android O+ account restrictions for **Google Apps**" but inside the code there is "When enabled, **all applications** on this device will be able to see email address of your Google Accounts without prior authorization."

So, does it apply to all apps or only to Google Apps?

**Comment by mar-v-in** [comment]
The functionality technically applies to all applications that have GET_ACCOUNTS (aka Contacts) permission. It is mostly useful for Google Apps, as other apps do not tend to blindly believe they have permissions to access the account when they don't. However with this option enabled there is nothing *preventing* them from accessing the email address (if they have GET_ACCOUNTS permission). This was the default behavior on Android before Oreo and still is the default behavior for apps that target any older version at compile time, so the impact on privacy is limited (as there are other ways to get the account email address and you still need the permission anyway).

**Comment by Eerovil** [comment]
Does this affect #790?

**Comment by mar-v-in** [comment]
Yes, this is a workaround for the issue that arises with Google Apps that are not able to discover the Google Account.

**Comment by caneleex** [comment]
@mar-v-in, could I ask if it is possible to have instant push notifications instead of "Ping interval 60 seconds, Automatic: *5 minutes* and other"?

**Comment by voidstarstar** [comment]
Are the Google apps that could need this bypass different from those in [`KNOWN_GOOGLE_PACKAGES`](https://github.com/microg/android_packages_apps_GmsCore/blob/30ed2720a0ecd3067fe760e801ecbdbe1b5ff5be/play-services-core/src/main/java/org/microg/gms/common/PackageUtils.java#L47-L63)?  If it's deemed appropriate to whitelist them, perhaps a similar approach could be used?

@caneleex Your question seems completely off topic to me.  If you're interested in notifications that are not delayed, you may be interested in Doze support that will be in the next version.  See #732.

**Comment by ale5000-git** [comment]
@mar-v-in: It is possible to have an option to limit it to KNOWN_GOOGLE_PACKAGES?

**Comment by mar-v-in** [comment]
Many Google Apps are affected by this issue, not only those currently in `KNOWN_GOOGLE_PACKAGES`, but also some non-Google apps (chromium forks). Also it's really a mess to implement this on a per package basis. As this only recovers the original Android before Oreo behavior (including check of `GET_ACCOUNTS` permission), it's not a huge issue to allow it for all apps. And after granting access to an app to use a specific account, you should also be able disable the option again (is only required to discover the account, not to use it).

**Comment by caneleex** [comment]
@voidstarstar any eta?

**Comment by voidstarstar** [comment]
@mar-v-in 
Ok, it sounds like a per package whitelist would not be feasible then.

From what I understood:
 * Lollipop and earlier would blindly grant all permissions at install time without a way to revoke them.
* Starting with Marshmallow, permissions were separated into "normal" and "dangerous" categories.  A normal permission would be granted blindly, similar to Lollipop.  A dangerous permission would prompt the user at run time to allow it at a granular level and the user would later be able to revoke it.  The `GET_ACCOUNTS` permission is in this "dangerous" category due to the privacy issues with giving out this info to apps.
* Unfortunately the Marshmallow permission changes were only enforced if apps targeted Marshmallow or newer, so any apps targeting Lollipop or earlier would have their run time permissions blindly accepted.  So starting with Oreo, the permission prompts were actually enforced regardless of the targeted version to prevent this loophole.


Maybe I misunderstand what this patch does.  Would this new option prevent the user from getting prompted for the `GET_ACCOUNTS` permission and instead blindly allow it for all apps (including apps that target Marshmallow and newer)?  If so, isn't this the same behavior as pre-M, not pre-O?  As long as this is implemented as an option that [is off by default](https://github.com/microg/android_packages_apps_GmsCore/commit/30ed2720a0ecd3067fe760e801ecbdbe1b5ff5be#diff-6acb9e7dd8e353edb651baa21b4f2de4R186), I think it would be fine for now, but it could possibly be improved in the future.


@caneleex I do not know.  You can still compile it yourself to get it today, however.

**Comment by mar-v-in** [comment]
Since Android O, apps targeting O+ will not be able to see accounts even after `GET_ACCOUNTS` was granted by default. Apps targeting pre-O are not affected and will be able to see accounts as soon as `GET_ACCOUNTS` is granted. Apps targeting pre-M will be granted `GET_ACCOUNTS` automatically and be able to see accounts directly.

This feature only affects Android O+ and apps targeting O+ after they were granted `GET_ACCOUNTS` permission.

**Comment by voidstarstar** [comment]
Thanks for clarifying.  I misunderstood the issue.  Sorry about that!

**Comment by caneleex** [comment]
@voidstarstar how?

**Comment by voidstarstar** [comment]
@caneleex https://github.com/microg/android_packages_apps_GmsCore/wiki/Building

This is off topic.  If you have questions about when the next release will be, you should take them to #788.

**Comment by ale5000-git** [comment]
Since the issue is now clear and the new version with the fix is released today I'm closing it now.
