### ISSUE TITLE
UnifiedNlp's update from F-Droid broke microg

### ISSUE THREAD

**Issue by RoiArthurB** [microg/android_packages_apps_GmsCore#811]
Hello,

Since the last update of UnifiedNlp from F-Droid (the update with MapBox - `0.2.7.17455`), all my microg is broken :
- My Google Accounts are not detected anymore (even when the option _enable detection_ is active on my GAccounts)
- Every apps using Google Location are crashing when they request my current position (Google Maps, Grab, Snapchat, etc)
- Safety Net is still failing all the time

I don't know which log could be helpful, so feel free to ask any of them

PS: I see on FDroid that I have both the version labeled `0.2.7.17455` and `0.2.7.17455-mapbox` are installed and I can't remove any one from them nor downgrade to the previous microg version which was working great :/

**Comment by Nanolx** [comment]
There's no unifiedNlp update, it's just a mislabed microG update, which is a known bug in F-Droid which occurs if two different repositories have the same app provided. In this case `com.google.android.gms` is both the standalone unifiedNlp (from F-Droid Main repo) and microG (from microG repo), so the F-Droid client is confused and doesn't know which package information to show.

1 + 2 are (mostly) fixed with the latest commits (not yet released), 3 is perfectly correct, as it's not "still" failing, it's "again" failing ;) - last Friday Google has made changes to `the.apk` (DroidGuard) and now microG's DroidGuardHelper is incompatible.

You can Downgrade microG by going to System Settings > Apps > microG Services Core > Burger-Menu > Uninstall updates. You'll then roll-back to the version installed in /system. Then go to F-Droid and update to the best working version for you (if required).

**Comment by sol8712** [comment]
The crashing must be app specific, I'm on Lineage/MicroG and on my Uber app it "seems" to work like before but I'm not currently moving so idk, on the DoorDash Dasher app it's a brand new map with "mapbox" on the bottom corner and it cannot find my location so it defaults to somwhere random in Europe(I'm in US).

It seems like the system version on my phone is the mapbox one(just updated to latest OTA update for June 4th), I'm unable to downgrade at all. Could I safely install a preveious version over in TWRP? Or shoild i just put the later dated apk in /system?

**Comment by n76** [comment]
There is a mapbox version and a non-mapbox version of the new microG apk. Both with the same version, etc. I found I could just install the non-mapbox version to get the old map functionality back.

That said, I've got a couple apps that were working well before I upgraded microG that are now crashing on start up regardless of mapbox or non-mapbox. My logcat looks similar to some posted on other issue reports so I haven't created a new issue or uploaded them as I figure the underlying problem(s) are being looked at.

**Comment by RoiArthurB** [comment]
@Nanolx Thanks for all your help! :D
So I've uninstall the last update and I'm now using again the `0.2.6.13280` version and I'm waiting for the new release which should fix every bug that I've got :)
Also, I'm not sure to clearly understand the problem with F-Droid.. Should I change something in FD's settings?

@sol8712 I'm also using Lineage/MicroG on my phone and the problem was when any app was trying to use GMS. For example, Google Maps was working fine until it try to fetch my location (I'm using Bouncer so the app request location permission everytime), but Here WeGo (which doesn't use GMS) could fetch my location and was working fine with the update (because it's not using GMS).

PS: I would like to take this message to ask you something. I'm using Lineage/MicroG on a oneplus3 and there's no system update since May 14... Do you know why? (I've saw that LineageOS continue to build some new release, so I'm wondering)

**Comment by ale5000-git** [comment]
@mar-v-in
@Nanolx

Until the map api is splitted in a different package the two version (mapbox and vtm) should have a different version code otherwise F-Droid will report "BOTH" as installed and suggested.

This will cause a lot of problems with users that won't know that version they had installed and blindly report bugs.

**Comment by Nanolx** [comment]
If you go into the microG settings the mapbox build has -mapbox appended to the version name (0.2.7.14755), the vtm build only displays the version (0.2.7.14755).

You can't use different version codes, as F-Droid would otherwise 'upgrade' you from one to another.

Am 5. Juni 2019 14:31:17 MESZ schrieb ale5000 <notifications@github.com>:
>@mar-v-in
>@Nanolx
>
>Until the map api is splitted in a different package the two version
>(mapbox and vtm) should have a different version code otherwise F-Droid
>will report "BOTH" as installed and suggested.
>
>This will cause a lot of problems with users that won't know that
>version they had installed and blindly report bugs.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/android_packages_apps_GmsCore/issues/811#issuecomment-499063006

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ale5000-git** [comment]
Yes, but F-Droid do not care about version name, it just use version code.
