### ISSUE TITLE
chrome crashes constantly after latest update

### ISSUE THREAD

**Issue by patrickdrd** [microg/android_packages_apps_GmsCore#860]
I uninstalled and reinstalled and no change, 
I think I have to restore from image

[2019-07-03-09-56-50.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3353659/2019-07-03-09-56-50.txt)
[2019-07-03-09-59-23.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3353660/2019-07-03-09-59-23.txt)

it's the second consecutive time I'm having issues with a microg update,
the first issue is still unsolved ("I cannot install update(s) on my other phone"):
https://github.com/microg/android_packages_apps_GmsCore/issues/813
I don't expect much in this either,

in my opinion, @mar-v-in should work on solving each and every issue and then dealing with the maps,
what use would the maps be to me (and all of us) if basic apps aren't working correctly?

I installed microg in order to avoid problems with google play services,
but I feel things are worse,
I have opened many issues and no reply at all:
https://github.com/microg/android_packages_apps_GmsCore/issues/created_by/patrickdrd
in some days when I'll have a bit more time I'll install google play apps again

edit: I restored from image and everything works as it used to,
my image is from 3 days ago, but, trust me, 
I didn't change anything since then, other than installing some irrelevant updates,
also chrome was working absolutely fine since yesterday night,
after installing microg latest... kaboom!

edit2: I tried the vtm, same problems (I initially tried the mapbox)

**Comment by patrickdrd** [comment]
is this for me?
https://github.com/microg/android_packages_apps_GmsCore/commit/8a0010a1d8beec67d05c01fb739e306c96e81d1c

@mar-v-in ??

**Comment by mar-v-in** [comment]
I cannot verify each and every app with every change I do. Most apps run pretty well with microG. The main purpose of microG is to get as many third-party apps functional as possible, but of course the priorities which apps should go first are very different for everyone.

The old maps implementation was causing heavy issues with many apps, rendering many ride/bike sharing and taxi apps completely unusable, which is critical for many users. On the other hand, your example Chrome to me sounds rather unimportant: There are tons of other Browsers out there, many with important features like Ad and Privacy blockers and fully open source, but still relying on the source of Chromium and thus having the same speed and compatibility - but not relying on any Google services at the same time.

Also please note that I usually read all issues and if I found that they require any action from me, I will do so. I don't always reply directly, especially in threads when the issue is not microG itself, but for example the custom ROM being used. (like your #813)

The commit 8a0010a1d8beec67d05c01fb739e306c96e81d1c fixes your issue. I uploaded a nightly version including this commit to https://microg.org/dl/GmsCore-v0.2.8.17785-2-8a0010a.apk for you to test.

**Comment by patrickdrd** [comment]
yes, it works, thanks a lot!

as for the browser opinion, no sir, I wouldn't agree with your point, because chrome is the only one (from the chromium family) that supports syncing abilities
(google has blocked sync in every other chromium browser in android  in case you didn't know),
which is absolutely important for me, because I use 3 different computers and 3 android devices and
I need my bookmarks and my passwords synced
I've got firefox installed too, but the difference is speed is.. at least notable,
and last but not least, chrome is used by way more people worldwide (how much is its percentage in android? 90%) than taxi and bike apps ,
so in my opinion is far more important that taxis and bikes,
anyway, thanks again for your work

**Comment by patrickdrd** [comment]
I also got another issue for long, I've got 40 registered apps and scrolling through them in the relevant section in microg settings causes a crash in gmscore

**Comment by Nanolx** [comment]
> how much is its percentage in android? 90%

The Chrome-Family (including Chromium or forks like Bromite) is about 66 %, see https://en.wikipedia.org/wiki/Usage_share_of_web_browsers#Summary_tables but: I from my experience the percentage is noticeably lower within the microG community.

> so in my opinion is far more important that taxis and bikes

following the microG thread on XDA, the bug tracker here and also ale5000's or my installer's threads, you'll see that in fact many microG users use something different than Chrome and wa~~y more post about the Maps issues rather than browser issues, so mar-v-in has set the priority correctly (many would argue that SafetyNet is also wa~~y important than browser support).

> I also got another issue for long, I've got 40 registered apps and scrolling through them in the relevant section in microg settings causes a crash in gmscore

Please open a new issue and post a log during the crash - as usual.

**Comment by patrickdrd** [comment]
> the issue is not microG itself, but for example the custom ROM being used. (like your #813)

I didn't know it was the custom rom to blame for this, you didn't say so, are you sure?
did you read the logcat?

> The old maps implementation

as for maps apps, I'm using here maps and google maps go and they worked with 0.2.6, 0.2.7 and they work with 0.2.8 too (I've just tested with the nightly)
I tried to install google maps (not the go) over the weekend and they weren't working so
I chose google maps go, because I needed it that time to find a poi and only google maps had it

**Comment by samantohermes** [comment]
Chromium-based browsers have an option to import and export bookmarks through a HTML file. And also, you can use KeePass (for Android, I recommend Keepass2Android)

**Comment by patrickdrd** [comment]
> Chromium-based browsers have an option to import and export bookmarks through a HTML file

it's not convenient to export and import all the time, don't you think?
and I'm saying that because I'm changing them quite often

also,
> you can use KeePass (for Android, I recommend Keepass2Android)

I tried lastpass a couple of times and I hated that implementation,
copying and pasting the password through another app is both insecure and inconvenient,
so, I'm not fan of them at all, sorry

**Comment by Nanolx** [comment]
> is both insecure and inconvenient

Depends. On Android Pie Google has implemented an interface (autofill service) for that kind of apps, which made it both much more secure and convinient. Below Pie it's less of both, that's right.

KeePass DX for example will show you a pop up with it offering login credentials inside your browser, but also has a "magic keyboard", which you can quickly switch to.

**Comment by ildar** [comment]
Marvin, i have Google Drive crashing with new release. I guess the bug may
be the same (can't check logcat till tomorrow)
Yet i cannot test the apk you shared because it's mapbox flavor. That
flavor doesn't fit yet to one app i have. Can you please build vtm so i can
test it?
Thanks!

**Comment by mar-v-in** [comment]
@ildar 

see https://microg.org/dl/GmsCore-v0.2.8.17785-2-8a0010a-vtm.apk

Can you tell which specific app is causes issues with the mapbox flavor for you?

**Comment by ildar** [comment]
Thanks!
The app of trouble: citybus.guidejet.com

**Comment by ildar** [comment]
Ahh! Great! Google Drive works again!
Thank you once more!

**Comment by drrossum** [comment]
Google Drive v2.19.212.04.45 works for me with GmsCore v0.2.8.17785-mapbox on Android Pie.  I have not tried updating Drive to the latest version (because I'm happy that it just works!).
