### ISSUE TITLE
Offline GPS not working

### ISSUE THREAD

**Issue by Arczi008TV** [microg/android_packages_apps_GmsCore#892]
GPS is working only with wifi enabled, but on offline maps not working. Tried few apps.

Galaxy S2 I9100

**Comment by CircuitSerialKiller** [comment]
Which of the checkboxes not checked in the Self-Check?

**Comment by Arczi008TV** [comment]
Only this one 
![1dc](https://user-images.githubusercontent.com/49120706/61582388-951a0f80-ab2a-11e9-8d69-78f0ebc8f600.PNG)

**Comment by CircuitSerialKiller** [comment]
What ROM are you using, what version of Android, and how did you install microG? Your built-in system location provider may be needed an may have been deleted. Or, you could try an xPosed UnifiedNlp module to get it working - I had to use XposedGmsCoreUnifiedNlp. 
What are you using to test GPS? Can you see if the app GPS Test Plus shows anything?

**Comment by Arczi008TV** [comment]
I have NeatROM based on android 4.1.2

https://microg.org/download.html
Downloaded from here com.google.android.gms and pasted it to system\apps
Then installed some addons from F-Droid Like mozilla

**Comment by CircuitSerialKiller** [comment]
Have you grabbed any logcats? I used the "Logcat Reader" app and it help tremendously to get things working on my device and find permission problems. Was GPS working on your ROM before installing microG? 
Also, there is a [zip installer](https://forum.xda-developers.com/android/development/microg-unofficial-installer-t3432360) for microG that @ale5000 was nice enough to make that you might want to take a look at. 
Before you decide to just install it though, read through install.sh and uninstall.sh. It made the mistake of just installing it without reading too much and it broke a whole bunch of stuff on my phone when it overwrote my privapp-permissions-google.xml file (newer Android OS's) and deleted my stock location provider which is needed on some devices in conjunction with microG. I ended up modifying the zip file a bit to my liking. 
Anyhow, you can read through those two scripts real easily and see if you have everything right. 
Also, I would grab the latest microG, which has a -4 at the end.

**Comment by Arczi008TV** [comment]
Its working in offline fine with google play services.  
Theres no any logs on logcat.

**Comment by voidstarstar** [comment]
This issue was closed, but isn't it still a bug?  I don't use GPS features myself, but workaround sounds odd.  Why would wifi need to be enabled (but not connected) to use offline GPS?

**Comment by n76** [comment]
> This issue was closed, but isn't it still a bug? I don't use GPS features myself, but workaround sounds odd. Why would wifi need to be enabled (but not connected) to use offline GPS?

Depends on the back end, but network location based providers need to be able to see what networks (WiFi, etc.) are in the area to determine where the phone is. This is very true of the local WiFi backend and for Déjà Vu. It has been a while since I read through the code for the Apple and Mozilla backends, but my recollection is they work mainly off of what WiFi networks are in the area too, they just need an external server available as well.

With respect to why GPS needs a network based location to work. . . This is less clear but I think it comes down to having a half way decent guess on location to start with helps in GPS acquisition. In theory, the GPS should acquire regardless. But if you have no rough location guess and can't get current satellite orbit data over the Internet ("assisted" GPS) then your GPS receiver may have to listen for the orbit data which can take 10 or 12 minutes if there is no data error on the weak signal. If there is a data error it can take much longer. I am not sure if that is also true of non-US satellite position systems (GLONASS, Galileo, etc.) but if your phone is GPS only then it is definitely true.

**Comment by Arczi008TV** [comment]
I have noticed my i9100 have problems even with google play services to get location in offline mode.
Enabled wifi doest change anything.
