### ISSUE TITLE
Error on Apps: Can't access Google Play Services

### ISSUE THREAD

**Issue by EMREOYUN** [microg/android_packages_apps_GmsCore#907]
Every app(expect microG) gets this error.

Latest microG apps installed.
Added one google account(No errors get while adding).
Offical Google Play Store installed(tried with FakeStore, same error happened).
Google Cloud Messaging and device registration enabled.
DroidGuard installed.
Can't check SafetyNet (can't access Google Play Services).
Spoof signature enabled and working on all Google Apps.

Android 5.1
Installed to system apps(also used XPosed)

Help please?

**Comment by EMREOYUN** [comment]
What a support :)

**Comment by mar-v-in** [comment]
Sorry, your report isn't helpful at all.
a) Is every checkbox in the microG Self-Check ticked?
b) Which app exactly were you using that showed an error and at which point do they do.

**Comment by EMREOYUN** [comment]
a) Yea i forgot to tell, all of checkboxes are ticked.
b) All apps (expect MicroG ones) gets error.

**Comment by Nanolx** [comment]
As a follow up: I googled for 'All apps (except microG ones)' but neither F-Droid nor Aurora Store gave me a proper result.

Joke aside: /what/ app is effected? Also, did you know that 'Play Services missing' may also /mean/ 'Play Store missing' instead? Do you have either Fake Store or Play Store installed? If not, installing one of those two (as privileged system app) may fix your issue.

**Comment by EMREOYUN** [comment]
This is the error:
![image](https://user-images.githubusercontent.com/35144629/62822541-b9976380-bb8d-11e9-96ad-3cc3d609dcab.png)

Tried Apps:
•Safetynet Tester
•ES File Editor (Purchase Screen)
•Some Games supports Google Play Games (no issues on logon but error getting user ID and not logging)

"Do you have either Fake Store or Play Store installed?"
•Yes and i writed in details of issue can be found up.
![image](https://user-images.githubusercontent.com/35144629/62822574-1a26a080-bb8e-11e9-9bfd-7c28293b35bd.png)

**Comment by Nanolx** [comment]
OK, what version of microG are you using? Latest is 0.2.8.17785.

If you're on the latest version, a logcat is required to see more, why that message appears (Play Games btw. is not supported at all).

**Comment by EMREOYUN** [comment]
This:
![image](https://user-images.githubusercontent.com/35144629/62822810-3415b280-bb91-11e9-8d16-d2ddb3fac3db.png)

**Comment by EMREOYUN** [comment]
What a support :) vol 2

**Comment by mar-v-in** [comment]
This is not a support channel but an issue tracker.

- SafetyNet is known to be non-functional in the moment due to changes on Google side, see https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/24
- Google Sign In API is not implemented, see https://github.com/microg/android_packages_apps_GmsCore/issues/600
- Google Play Games is not implemented, see https://github.com/microg/android_packages_apps_GmsCore/issues/163
- Android Payment API is not implemented, see https://github.com/microg/android_packages_apps_GmsCore/issues/361

Also, you might want to give some details on the OS and device you are running, because from the screenshots it doesn't look like being a standard AOSP or LineageOS.

I am closing this issue as duplicate for now.

**Comment by EMREOYUN** [comment]
Not Helped :-1:
