### ISSUE TITLE
Impossible to register UnifiedNIp in system

### ISSUE THREAD

**Issue by LoHub** [microg/android_packages_apps_GmsCore#940]
Hello everyone,
I am not able to use UnifiedNIp for localisation.

All looks good in microG self-check panel before UnifiedNIp registering.
* [x] System spoof signature
* [x] Installed Pakcage
    * [x] GMSCore
    * [x] Phonesky
    * [x] GSF
* [x] Persmission granted
* [x] System support location provider
* [ ] UnifiedNIp is registered in system

Additionaly I installed and activated
* 4 backends (Déjà vu, Mozilla, Radiocells.org, Nominatim)
* XposedGmsCoreUnifedNIp

I restarted the system many times.

Technicals details
------------------
* LG G5 H850 arm64
* Lineage OS 15.1 (Anrdoid Oreo 8.1.0) (from https://forum.xda-developers.com/lg-g5/development/rom-unofficial-lineageos-15-1-g5-t3806842)
* XPosed 90 beta3
* MicroG 0.2.8.17785-mapbox
* XposedGmsCoreUnifedNIp1.0.4-Beta
* No Google Account configured
* No GAPPS
* Rooted device

Potential probelmatic additional packages
------------------------------------------
* XPrivacyLua (but disable for Microg, XposedGmsCoreUnifedNIp and backends)
* Greenify

Does anyone have an idea?
If you need any additonal information, please just ask.
Thank you all!

Sorry for the doublon with #925. My previous post was hidden by GitHub.

**Comment by imShara** [comment]
Same here with AEX. Solved by installation mozilla nlp from f-droid, but i think it's hack, not soluton

**Comment by LoHub** [comment]
Unfortunately, in my case, MozillaNIpBackend is already installed and UnifiedNIp is still not recognize in system.

**Comment by emdemir** [comment]
Same issue here. I get "0 backends configured" but I have MozillaNlpBackend and GSM Location installed. Moving their `/data/app` folders to `/system/priv-app` did nothing. Android 9 (Lineage 16.1) on klte, microG 0.2.8-17785-mapbox.

**Comment by Nanolx** [comment]
On some older ROMs (pre-Pie) you may have to get rid of the included location provider first, for example `com.qualcomm.location` or the-like from `/system/priv-app`.

**Comment by mar-v-in** [comment]
On devices/systems using file based encryption (FBE), which include all devices running Android 10 and many devices that originally shipped with Android 7 or higher, microG/UnifiedNlp currently must be installed on /system (either app or priv-app) so that it can register to the system. UnifiedNlp backends don't need to be installed to /system, though it certainly wouldn't hurt.

Some ROMs do not have support for proper network location providers on some devices. That's an upstream issue, caused by the device code setting `config_enableNetworkLocationOverlay` and `config_enableFusedLocationOverlay` to `false`. In such a case the message "Your system does not support this UnifiedNlp package." will be displayed in Self-Check. The XposedGmsCoreUnifedNIp module can help in such cases, though upstream fixes are definitely favorable.

**Comment by LoHub** [comment]
I finally solved my issue by installing the Magisk Microg Installer. Now it works fine.
Thank you all for your help.
