### ISSUE TITLE
google maps token error (GmsAuthManager token present, but expired)

### ISSUE THREAD

**Issue by patrickdrd** [microg/android_packages_apps_GmsCore#973]
I cannot login to google maps (I'm running 7.7 version for many reasons:
1) it was the latest one I could sign with my key (so that it wouldn't show updates on play store)
2) it uses much lower ram than the latest version and I don't have plenty of it left,
etc..):

@mar-v-in can you please check my logcat?

[2019-11-04-15-16-25.txt][redacted for privacy]

**Comment by mar-v-in** [comment]
From the log:
```
java.io.IOException: Error=UNREGISTERED_ON_API_CONSOLE
```

Google denies login for this app, independently from that it's using microG. This could be because it's outdated or because you changed the signature. In the latter case it could help to use signature spoofing by modifying the Manifest of your modded Google Maps app.

Custom mods of outdated versions of Google Maps are certainly out of scope for microG. I will close this issue as it seems not microG related.

**Comment by patrickdrd** [comment]
> signature spoofing by modifying the Manifest

yes, without modifying signature it works,
but I don't know how to spoof the signature :(

**Comment by patrickdrd** [comment]
anyway, I installed 9.75.1 you suggested here:
https://github.com/microg/android_packages_apps_GmsCore/issues/709#issuecomment-464791741

and everything is working besides it being shown for update on play store,
latest version doesn't work because it requires google play services updates (even though I'm running microg 0.2.10

**Comment by mar-v-in** [comment]
When you see the "Update Google Play services" message, don't touch it's only "Update" button, instead touch "outside" the message (in the grayed-out area) to dismiss it.
